# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
#  - osx
julia:
  - 0.7
#  - nightly
notifications:
  email: false
# getting latest master of ArgCheck
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia test_script.jl
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("ContinuousTransformations")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("ContinuousTransformations")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  # deploy documentation
  - julia -e 'cd(Pkg.dir("ContinuousTransformations")); include(joinpath("docs", "make.jl"))'
git:
  depth: 9999999
